[package]
name = "riscv-sandbox"
version = "0.2.0"
authors = ["Arthur Blanleuil <arthur.blanleuil@inria.fr>"]
description = "RISC-V implementation for educational purpose."
license = "MIT"

[dependencies]
elf = "^0.0.10"
